import requests
import json

headers = {'Origin': 'https://app.cpcbccr.com'}
headers['Accept-Encoding'] ="gzip, deflate, br"
headers['Accept-Language'] ="en-GB,en-US;q=0.9,en;q=0.8"
headers['User-Agent'] ="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"
headers['Content-Type'] ="application/x-www-form-urlencoded"
headers['Accept'] ="application/json, text/plain, */*"
headers['Referer'] ="https://app.cpcbccr.com/ccr/"
headers['Connection'] ="keep-alive"
headers['Host'] ="app.cpcbccr.com"

#encoded_data = "eyJkcmF3IjoxLCJjb2x1bW5zIjpbeyJkYXRhIjowLCJuYW1lIjoiIiwic2VhcmNoYWJsZSI6dHJ1ZSwib3JkZXJhYmxlIjpmYWxzZSwic2VhcmNoIjp7InZhbHVlIjoiIiwicmVnZXgiOmZhbHNlfX1dLCJvcmRlciI6W10sInN0YXJ0IjowLCJsZW5ndGgiOjUwLCJzZWFyY2giOnsidmFsdWUiOiIiLCJyZWdleCI6ZmFsc2V9LCJmaWx0ZXJzVG9BcHBseSI6eyJwYXJhbWV0ZXJfbGlzdCI6W3siaWQiOjcsIml0ZW1OYW1lIjoiUE0yLjUiLCJpdGVtVmFsdWUiOiJwYXJhbWV0ZXJfMTkzIn1dLCJjcml0ZXJpYSI6IjQgSG91cnMiLCJyZXBvcnRGb3JtYXQiOiJUYWJ1bGFyIiwiZnJvbURhdGUiOiIxNC0xMC0yMDE3IFQwMDowMDowMFoiLCJ0b0RhdGUiOiIyMi0xMC0yMDE3IFQwMDowMDowMFoiLCJzdGF0ZSI6IlV0dGFyIFByYWRlc2giLCJjaXR5IjoiS2FucHVyIiwic3RhdGlvbiI6InNpdGVfMjc2IiwicGFyYW1ldGVyIjpbInBhcmFtZXRlcl8xOTMiXSwicGFyYW1ldGVyTmFtZXMiOlsiUE0yLjUiXX0sInBhZ2luYXRpb24iOjF9"



encoded_data="ewogICAgImRyYXciOiAxLAogICAgImNvbHVtbnMiOiBbCiAgICAgICAgewogICAgICAgICAgICAiZGF0YSI6IDAsCiAgICAgICAgICAgICJuYW1lIjogIiIsCiAgICAgICAgICAgICJzZWFyY2hhYmxlIjogdHJ1ZSwKICAgICAgICAgICAgIm9yZGVyYWJsZSI6IGZhbHNlLAogICAgICAgICAgICAic2VhcmNoIjogewogICAgICAgICAgICAgICAgInZhbHVlIjogIiIsCiAgICAgICAgICAgICAgICAicmVnZXgiOiBmYWxzZQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgXSwKICAgICJvcmRlciI6IFtdLAogICAgInN0YXJ0IjogMCwKICAgICJsZW5ndGgiOiA1MCwKICAgICJzZWFyY2giOiB7CiAgICAgICAgInZhbHVlIjogIiIsCiAgICAgICAgInJlZ2V4IjogZmFsc2UKICAgIH0sCiAgICAiZmlsdGVyc1RvQXBwbHkiOiB7CiAgICAgICAgCiAgICAgICAgImNyaXRlcmlhIjogIjQgSG91cnMiLAogICAgICAgICJyZXBvcnRGb3JtYXQiOiAiVGFidWxhciIsCiAgICAgICAgImZyb21EYXRlIjogIjIyLTEwLTIwMTcgVDAwOjAwOjAwWiIsCiAgICAgICAgInRvRGF0ZSI6ICIzMC0xMC0yMDE3IFQwMDowMDowMFoiLAogICAgICAgICJzdGF0ZSI6ICJEZWxoaSIsCiAgICAgICAgImNpdHkiOiAiRGVsaGkiLAogICAgICAgICJzdGF0aW9uIjogInNpdGVfMzAxIiwKICAgICAgICAicGFyYW1ldGVyIjpbInBhcmFtZXRlcl8yMDQiLCJwYXJhbWV0ZXJfMjM4IiwicGFyYW1ldGVyXzIxNSIsInBhcmFtZXRlcl8xOTMiLCJwYXJhbWV0ZXJfMjM1IiwicGFyYW1ldGVyXzIzNyIsInBhcmFtZXRlcl8xOTgiLCJwYXJhbWV0ZXJfMjMyIiwicGFyYW1ldGVyXzIzNCIsInBhcmFtZXRlcl8yMzMiLCJwYXJhbWV0ZXJfMjAzIiwicGFyYW1ldGVyXzIwMiIsInBhcmFtZXRlcl8zMjQiLCJwYXJhbWV0ZXJfMzExIiwicGFyYW1ldGVyXzIyNiIsInBhcmFtZXRlcl8xOTQiLCJwYXJhbWV0ZXJfMjI1IiwicGFyYW1ldGVyXzIyMiIsInBhcmFtZXRlcl8zMTIiXSAsCiAgICAgICAgInBhcmFtZXRlck5hbWVzIjogWyJBVCIsIkJQIiwiUE0xMCIsIlBNMi41IiwiUkgiLCJTUiIsIlRlbXAiLCJUb2x1ZW5lIiwiV0QiLCJXUyIsIkNPIiwiQmVuemVuZSIsIlAtWHlsZW5lIiwiTkgzIiwiTk8iLCJOTzIiLCJOT3giLCJPem9uZSIsIlNPMiJdCiAgICB9LAogICAgInBhZ2luYXRpb24iOiAxCn0="
r = requests.post("https://app.cpcbccr.com/caaqms/fetch_table_data", headers=headers, data=encoded_data, verify=False)


#Mumbai -1  , Navi Mumbai -2017
# Bangalore - 2/3 - 2017
# Delhi - 5 stations 2017
# 10 stations - which have data from 2017 to 2020.
####2017
stationList = [{"city":"Delhi", "station":"site_301", "state":"Delhi"}]
#Yamini to populate
###


# ---> One person can check on duration and pagination fromDate=2017
	###
###

#

#
	#
	#Creating csv for all JSON calls
#



if r.status_code == 200:
	print("Awesome response code 200")
	json_data = json.dumps(r.json())
	print(json_data)
	#json_data_hash = hashlib.md5(json_data)
	#row_exists['json_data'] = json_data
	#row_exists['json_data_hash'] = json_data_hash.hexdigest()
	#row_exists['status_code'] = r.status_code


enc="eyJkcmF3IjoxLCJjb2x1bW5zIjpbeyJkYXRhIjowLCJuYW1lIjoiIiwic2VhcmNoYWJsZSI6dHJ1ZSwib3JkZXJhYmxlIjpmYWxzZSwic2VhcmNoIjp7InZhbHVlIjoiIiwicmVnZXgiOmZhbHNlfX1dLCJvcmRlciI6W10sInN0YXJ0IjowLCJsZW5ndGgiOjUwLCJzZWFyY2giOnsidmFsdWUiOiIiLCJyZWdleCI6ZmFsc2V9LCJmaWx0ZXJzVG9BcHBseSI6eyJwYXJhbWV0ZXJfbGlzdCI6W3siaWQiOjcsIml0ZW1OYW1lIjoiUE0yLjUiLCJpdGVtVmFsdWUiOiJwYXJhbWV0ZXJfMTkzIn1dLCJjcml0ZXJpYSI6IjQgSG91cnMiLCJyZXBvcnRGb3JtYXQiOiJUYWJ1bGFyIiwiZnJvbURhdGUiOiIxNC0xMC0yMDE3IFQwMDowMDowMFoiLCJ0b0RhdGUiOiIyMi0xMC0yMDE3IFQwMDowMDowMFoiLCJzdGF0ZSI6IlV0dGFyIFByYWRlc2giLCJjaXR5IjoiS2FucHVyIiwic3RhdGlvbiI6InNpdGVfMjc2IiwicGFyYW1ldGVyIjpbInBhcmFtZXRlcl8xOTMiXSwicGFyYW1ldGVyTmFtZXMiOlsiUE0yLjUiXX0sInBhZ2luYXRpb24iOjF9"